name: Lillian Nakato

on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Compatible with Django 5.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django==5.2.4
          pip install -r requirements.txt  # If you have additional dependencies

      - name: Run Django tests
        run: |
          python manage.py test